name: ZMK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and initialize west
        run: |
          pip install west
          west init -l .
          west update
          west zephyr-export
          pip install -r ../zephyr/scripts/requirements-base.txt

      - name: Build firmware
        run: |
          ls ../zmk/app
          west build -s ../zmk/app -b keychron -d build/keychron_b1_us -- -DSHIELD=keychron_b1_us

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/keychron_b1_us/zephyr/zmk.uf2