name: ZMK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          path: config

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and initialize west
        run: |
          cd config
          pip install west
          west init -l .
          west update
          west zephyr-export
          pip install -r ../zephyr/scripts/requirements-base.txt

      - name: 🔍 Debug Show nanopb module.yml
        run: |
          cd config
          echo "===== pwd ====="
          pwd
          echo "===== ls -R modules/lib/nanopb ====="
          ls -R modules/lib/nanopb || echo "modules/lib/nanopb not found"
          echo "===== module.yml ====="
          cat modules/lib/nanopb/zephyr/module.yml || echo "module.yml not found"
          echo "===== HEAD ====="
          cd modules/lib/nanopb || exit 1
          git log -1 || echo "no log"

      - name: Build firmware
        run: |
          cd config
          ls ../zmk/app
          west build -s ../zmk/app -b keychron -d build/keychron_b1_us -- -DSHIELD=keychron_b1_us

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: config/build/keychron_b1_us/zephyr/zmk.uf2